//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
package com.openbravo.pos.catalog;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 * Panel de catálogo modernizado con mejor distribución de productos
 * @author Sebastian - Versión mejorada
 */
public class JCatalogTab extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    
    private static final int CATALOG_BUTTON_WITH = 170; // Aumentado para mejor apariencia
    private static final int CATALOG_BUTTON_HEIGHT = 200; // Aumentado para mejor proporción

    private final JFlowPanel flowpanel;

    public JCatalogTab() {
        initComponents();

        flowpanel = new JFlowPanel();
        
        JScrollPane scroll = new JScrollPane(flowpanel);
        scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        scroll.getVerticalScrollBar().setPreferredSize(new Dimension(12, 12)); // Scrollbar más delgado
        scroll.setBorder(null); // Sin borde para apariencia limpia
        scroll.getViewport().setBackground(new Color(248, 250, 252));
        scroll.getVerticalScrollBar().setUnitIncrement(16); // Desplazamiento más suave

        add(scroll, BorderLayout.CENTER);
    }

    @Override
    public void setEnabled(boolean value) {
        flowpanel.setEnabled(value);
        super.setEnabled(value);
    }

    public void addButton(Icon icon, ActionListener actionListener, String text, String textTip) {
        
        CatalogItem item = new CatalogItem(text);
        item.setTextTip(textTip);
        // Convertir Icon a Image si es necesario
        if (icon instanceof ImageIcon) {
            item.setImage(((ImageIcon)icon).getImage());
        }
        ProductCardV3 prodCard = new ProductCardV3(item, actionListener);
        
        flowpanel.add(prodCard);
    }
    
    public void addCatalogItem(CatalogItem catalogItem, ActionListener actionListener) {
        ProductCardV3 prodCard = new ProductCardV3(catalogItem, actionListener);
        flowpanel.add(prodCard);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
