package com.openbravo.pos.sales;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.MessageInf;
import com.openbravo.data.loader.LocalRes;
import com.openbravo.pos.forms.AppLocal;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
import com.openbravo.pos.ticket.TicketLineInfo;

/**
 * Validates and edits units for a ticket line.
 */
public class JDialogUnits extends javax.swing.JDialog {

    private double m_dUnits;
    private boolean m_bOK;

    /** Creates new form JDialogUnits */
    private JDialogUnits(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private JDialogUnits(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static JDialogUnits getDialog(Component parent, TicketLineInfo line) {
        Window window = getWindow(parent);
        JDialogUnits myMsg;
        if (window instanceof Frame) {
            myMsg = new JDialogUnits((Frame) window, true);
        } else {
            myMsg = new JDialogUnits((Dialog) window, true);
        }
        myMsg.init(line);
        return myMsg;
    }

    private static Window getWindow(Component parent) {
        if (parent == null) {
            return new javax.swing.JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }

    private void init(TicketLineInfo line) {
        m_dUnits = line.getMultiply();
        m_bOK = false;

        // Set Product Info
        jLblProduct.setText(line.getProductName());
        jLblPrice.setText(com.openbravo.format.Formats.CURRENCY.formatValue(line.getPrice()));

        // Set Units
        jTxtUnits.setText(com.openbravo.format.Formats.DOUBLE.formatValue(m_dUnits));
        jTxtUnits.selectAll();

        // Root Pane Action for ESC
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                "cancel");
        getRootPane().getActionMap().put("cancel", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        // Arrow Keys for Increment/Decrement
        // We add this to the text field directly to ensure it works when focused
        jTxtUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_UP) {
                    incrementUnits(1.0);
                } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                    incrementUnits(-1.0);
                }
            }
        });
    }

    private void incrementUnits(double amount) {
        try {
            double current = Double.parseDouble(jTxtUnits.getText());
            current += amount;
            jTxtUnits.setText(com.openbravo.format.Formats.DOUBLE.formatValue(current));
            // Keep selection to allow easy overwrite
            jTxtUnits.selectAll();
        } catch (NumberFormatException e) {
            // Ignore if invalid
        }
    }

    public boolean isOK() {
        return m_bOK;
    }

    public double getUnits() {
        return m_dUnits;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblProduct = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLblPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtUnits = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnCancel = new javax.swing.JButton();
        jBtnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Unidades");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Producto:");
        jPanel1.add(jLabel1);

        jLblProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblProduct.setText("Nombre Producto");
        jPanel1.add(jLblProduct);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3);

        jLblPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblPrice.setText("0.00");
        jPanel1.add(jLblPrice);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Unidades:");
        jPanel1.add(jLabel5);

        jTxtUnits.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtUnits.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTxtUnits);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnCancel.setText("Cancelar");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancel);

        jBtnOK.setText("Aceptar");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnOK);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(400, 200));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            m_dUnits = Double.parseDouble(jTxtUnits.getText());
            m_bOK = true;
            dispose();
        } catch (NumberFormatException e) {
            java.awt.Toolkit.getDefaultToolkit().beep();
            jTxtUnits.selectAll();
            jTxtUnits.requestFocus();
        }
    }

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblPrice;
    private javax.swing.JLabel jLblProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtUnits;
    // End of variables declaration
}
